import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedProfil {
  final List<ProfilModel> results;

  AutogeneratedProfil({this.results});

  factory AutogeneratedProfil.fromJson(Map<String, dynamic> json) {
    List<ProfilModel> temp;
    if (json['results'] != null) {
      temp = new List<ProfilModel>();
      json['results'].forEach((v) {
        temp.add(new ProfilModel.fromJson(v));
      });
    }
    return AutogeneratedProfil(results: temp);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ProfilModel extends Equatable {
  final int id;
  final String name;

  ProfilModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory ProfilModel.fromJson(Map<String, dynamic> json) {
    return ProfilModel(json['id'], json['name']);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
