import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedLogin {
  final List<LoginModel> results;

  AutogeneratedLogin({this.results});

  factory AutogeneratedLogin.fromJson(Map<String, dynamic> json) {
    List<LoginModel> temp;
    if (json['results'] != null) {
      temp = new List<LoginModel>();
      json['results'].forEach((v) {
        temp.add(new LoginModel.fromJson(v));
      });
    }
    return AutogeneratedLogin(results: temp);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class LoginModel extends Equatable {
  final int id;
  final String name;

  LoginModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory LoginModel.fromJson(Map<String, dynamic> json) {
    return LoginModel(json['id'], json['name']);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
